[tox]
requires =
    tox>=4.11
env_list =
    test
    format-check
    type  # uncomment this when using type hints to enable type checking

[testenv]
base_python = 3.13

[testenv:test]
description = Run unit tests and output coverage report
extras =
    test
commands =
    coverage run -m pytest
    coverage report

[testenv:format-check]
description = Check code is compliant with ruff
skip_install = true
deps =
    {[testenv:format]deps}
commands =
    ruff check {posargs}
    ruff format --diff {posargs}
    pyproject-fmt pyproject.toml --check

[testenv:type]
description = Run type checking using mypy
deps =
    mypy==1.11.0
commands =
    mypy src --install-types --non-interactive {posargs}

[testenv:format]
description = Automatically format and lint code using ruff
skip_install = true
deps =
    pyproject-fmt==2.8
    ruff==0.14.2
commands =
    ruff check --fix {posargs}
    ruff format {posargs}
    - pyproject-fmt pyproject.toml

